changelog:
  categories:
    - title: "🚀 核心特性 (New Features)"
      labels:
        - "feature"
        - "enhancement"
    - title: "🐛 漏洞修复 (Bug Fixes)"
      labels:
        - "bug"
        - "hotfix"
    - title: "📝 文档更新 (Documentation)"
      labels:
        - "documentation"
    - title: "🐳 运维与底座 (Infrastructure)"
      labels:
        - "ci"
        - "docker"
  exclude:
    labels:
      - "ignore-for-release"