services:
  cpu:
    image: ghcr.io/${PEKNO_IMAGE_OWNER:-sat1n}/pekno-worker-cpu:${PEKNO_IMAGE_TAG:-latest}
    container_name: pekno-worker
    environment:
      WORKER_EXECUTION_MODE: cpu

  cuda:
    image: ghcr.io/${PEKNO_IMAGE_OWNER:-sat1n}/pekno-worker-cuda12:${PEKNO_IMAGE_TAG:-latest}
    container_name: pekno-worker
    environment:
      WORKER_EXECUTION_MODE: cuda
      NVIDIA_VISIBLE_DEVICES: ${NVIDIA_VISIBLE_DEVICES:-all}
      NVIDIA_DRIVER_CAPABILITIES: ${NVIDIA_DRIVER_CAPABILITIES:-compute,utility}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: ${NVIDIA_GPU_COUNT:-all}
              capabilities:
                - gpu
