"""add ai processing status

Revision ID: 6be3e5703b2d
Revises: 7a08e96b242d
Create Date: 2026-04-24 16:51:59.769339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6be3e5703b2d'
down_revision: Union[str, Sequence[str], None] = '7a08e96b242d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('ai_processing_status', sa.String(), server_default='completed', nullable=False))
    op.create_index(op.f('ix_items_ai_processing_status'), 'items', ['ai_processing_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_ai_processing_status'), table_name='items')
    op.drop_column('items', 'ai_processing_status')
    # ### end Alembic commands ###
