from __future__ import annotations

import json
import os
import tempfile
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any

from sqlalchemy import select
from sqlalchemy.dialects.postgresql import insert

from shared.api_errors import ApiError
from shared.constants import PLATFORM_WHITELIST
from shared.crypto import decrypt_value, encrypt_value
from shared.database import AsyncSessionLocal
from shared.error_codes import ERR_CREDENTIAL_UNREADABLE, ERR_INVALID_INPUT
from shared.models import UserCredentialORM


def validate_platform(platform: str) -> str:
    normalized = (platform or "").strip().lower()
    if normalized not in PLATFORM_WHITELIST:
        raise ApiError(
            ERR_INVALID_INPUT,
            f"Unsupported credential platform: {platform}",
            status_code=400,
        )
    return normalized


def validate_required_credentials(required_credentials: list[str] | None) -> list[str]:
    normalized: list[str] = []
    for platform in required_credentials or []:
        validated = validate_platform(platform)
        if validated not in normalized:
            normalized.append(validated)
    return normalized


# ---------------------------------------------------------------------------
# Cookie format detection & parsing
# ---------------------------------------------------------------------------

def detect_cookie_format(raw_input: str) -> str:
    """Detect whether input is a Netscape cookie file or a cookie string.

    Returns "netscape_file" or "cookie_string".
    """
    stripped = raw_input.strip()
    if stripped.startswith("# Netscape") or stripped.startswith("# Netscape HTTP Cookie File"):
        return "netscape_file"
    # Netscape files contain tab-separated columns; cookie strings contain "; "
    if "\t" in stripped and "\n" in stripped:
        # Could be Netscape — check for typical tab-separated cookie lines
        for line in stripped.splitlines():
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.split("\t")
            if len(parts) >= 6:
                return "netscape_file"
    return "cookie_string"


def parse_cookie_string(cookie_str: str) -> dict[str, str]:
    """Parse a semicolon-separated cookie string into {name: value} dict.

    Example input: "SESSDATA=abc123; bili_jct=def456; buvid3=ghi789"
    """
    cookies: dict[str, str] = {}
    for part in cookie_str.split(";"):
        part = part.strip()
        if not part or "=" not in part:
            continue
        name, _, value = part.partition("=")
        name = name.strip()
        value = value.strip()
        if name:
            cookies[name] = value
    return cookies


def parse_netscape_to_dict(file_content: str) -> dict[str, str]:
    """Parse Netscape cookie file content into {name: value} dict.

    Extracts all cookie entries (skipping comments/blank lines).
    """
    cookies: dict[str, str] = {}
    for line in file_content.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split("\t")
        if len(parts) >= 7:
            name, value = parts[5], parts[6]
            cookies[name] = value
    return cookies


def cookie_dict_to_header(cookies: dict[str, str]) -> str:
    """Build a Cookie header string from a {name: value} dict."""
    return "; ".join(f"{k}={v}" for k, v in cookies.items())


def cookie_string_to_netscape(cookie_str: str) -> str:
    """Convert a cookie string to Netscape file format.

    Uses .bilibili.com as default domain with 1-year expiry.
    """
    cookies = parse_cookie_string(cookie_str)
    expiry = int((datetime.now() + timedelta(days=365)).timestamp())
    lines = ["# Netscape HTTP Cookie File", "# This file is generated by Pekno. Do not edit.", ""]
    for name, value in cookies.items():
        lines.append(f".bilibili.com\tTRUE\t/\tTRUE\t{expiry}\t{name}\t{value}")
    return "\n".join(lines) + "\n"


def parse_stored_cookie(raw_value: str) -> tuple[str, dict[str, str]]:
    """Decrypt and parse stored cookie credential.

    Returns (format, cookie_dict) where format is "cookie_string" or "netscape_file".
    """
    decrypted = _decrypt_token_value(raw_value)
    try:
        data = json.loads(decrypted)
        fmt = data.get("format", "cookie_string")
        value = data.get("value", "")
    except (json.JSONDecodeError, AttributeError):
        # Legacy: raw value without JSON wrapper
        fmt = detect_cookie_format(decrypted)
        value = decrypted

    if fmt == "netscape_file":
        return fmt, parse_netscape_to_dict(value)
    return fmt, parse_cookie_string(value)


def build_cookie_header(user_id: str, platform: str) -> str | None:
    """Build a Cookie header string from stored credential.

    Returns the header value (e.g. "SESSDATA=xxx; bili_jct=yyy") or None.
    """
    credential = _get_credential_sync(user_id, platform)
    if not credential:
        return None
    _, cookie_dict = parse_stored_cookie(credential.token_value)
    if not cookie_dict:
        return None
    return cookie_dict_to_header(cookie_dict)


def _get_credential_sync(user_id: str, platform: str) -> UserCredentialORM | None:
    """Synchronous credential lookup for use in sync contexts."""
    import asyncio
    try:
        loop = asyncio.get_running_loop()
    except RuntimeError:
        loop = None

    if loop and loop.is_running():
        # We're inside an async context — can't use run_until_complete.
        # Return None; callers should use async version instead.
        return None

    from shared.database import AsyncSessionLocal as _Session
    import asyncio as _aio

    async def _fetch():
        async with _Session() as session:
            result = await session.execute(
                select(UserCredentialORM).where(
                    UserCredentialORM.user_id == user_id,
                    UserCredentialORM.platform == platform,
                )
            )
            return result.scalar_one_or_none()

    return _aio.run(_fetch())


def generate_cookie_file(user_id: str, platform: str) -> str | None:
    """Generate a temporary Netscape cookie file from stored credential.

    Returns the file path, or None if no credential found.
    """
    credential = _get_credential_sync(user_id, platform)
    if not credential:
        return None

    fmt, cookie_dict = parse_stored_cookie(credential.token_value)
    if not cookie_dict:
        return None

    if fmt == "netscape_file":
        # Already Netscape — decrypt and write directly
        decrypted = _decrypt_token_value(credential.token_value)
        try:
            data = json.loads(decrypted)
            content = data.get("value", "")
        except (json.JSONDecodeError, AttributeError):
            content = decrypted
    else:
        # Cookie string — convert to Netscape
        content = cookie_string_to_netscape(
            cookie_dict_to_header(cookie_dict)
        )

    # Write to a persistent temp file (cleaned up by OS or cron)
    tmp_dir = Path(tempfile.gettempdir()) / "pekno_cookies" / user_id
    tmp_dir.mkdir(parents=True, exist_ok=True)
    tmp_path = tmp_dir / f"{platform}_cookies.txt"
    tmp_path.write_text(content, encoding="utf-8")
    return str(tmp_path)


def get_cookie_fields_for_display(user_id: str, platform: str) -> list[dict[str, str]]:
    """Parse stored cookie and return masked fields for UI display.

    Returns [{"name": "SESSDATA", "masked_value": "2bc***I1U"}, ...]
    """
    credential = _get_credential_sync(user_id, platform)
    if not credential:
        return []

    _, cookie_dict = parse_stored_cookie(credential.token_value)
    return _build_fields_list(cookie_dict)


async def get_cookie_fields_for_display_async(user_id: str, platform: str) -> list[dict[str, str]]:
    """Async version of get_cookie_fields_for_display."""
    async with AsyncSessionLocal() as session:
        result = await session.execute(
            select(UserCredentialORM).where(
                UserCredentialORM.user_id == user_id,
                UserCredentialORM.platform == platform,
            )
        )
        credential = result.scalar_one_or_none()
    if not credential:
        return []

    _, cookie_dict = parse_stored_cookie(credential.token_value)
    return _build_fields_list(cookie_dict)


def _build_fields_list(cookie_dict: dict[str, str]) -> list[dict[str, str]]:
    fields = []
    for name, value in cookie_dict.items():
        fields.append({
            "name": name,
            "masked_value": mask_credential(value) or "",
        })
    return fields


def mask_credential(token_value: str | None) -> str | None:
    if not token_value:
        return None
    value = token_value.strip()
    if len(value) <= 8:
        return "*" * len(value)
    return f"{value[:4]}***{value[-3:]}"


def _decrypt_token_value(raw_value: str | None) -> str:
    value = raw_value or ""
    decrypted = decrypt_value(value)
    if decrypted is None:
        raise ApiError(
            ERR_CREDENTIAL_UNREADABLE,
            "The stored credential cannot be decrypted. Please re-enter it.",
            status_code=400,
        )
    return decrypted


def _resolve_token_value(raw_value: str | None) -> str:
    value = (raw_value or "").strip()
    if not value:
        return ""
    # Response builders may receive either an encrypted DB value or an already
    # decrypted/plaintext value from upstream helpers.
    if value.startswith("gAAAAA"):
        return _decrypt_token_value(value)
    return value


async def list_user_credentials(user_id: str) -> list[UserCredentialORM]:
    async with AsyncSessionLocal() as session:
        result = await session.execute(
            select(UserCredentialORM)
            .where(UserCredentialORM.user_id == user_id)
            .order_by(UserCredentialORM.platform.asc())
        )
        credentials = list(result.scalars().all())
        for credential in credentials:
            credential.token_value = _decrypt_token_value(credential.token_value)
        return credentials


async def get_user_credential(user_id: str, platform: str) -> UserCredentialORM | None:
    normalized = validate_platform(platform)
    async with AsyncSessionLocal() as session:
        result = await session.execute(
            select(UserCredentialORM).where(
                UserCredentialORM.user_id == user_id,
                UserCredentialORM.platform == normalized,
            )
        )
        credential = result.scalar_one_or_none()
        if credential:
            credential.token_value = _decrypt_token_value(credential.token_value)
        return credential


async def upsert_user_credential(user_id: str, platform: str, token_value: str) -> UserCredentialORM:
    from shared.time_utils import now_in_app_timezone_naive as _now

    normalized = validate_platform(platform)
    sanitized = (token_value or "").strip()
    if not sanitized:
        raise ApiError(ERR_INVALID_INPUT, "Credential value cannot be empty.", status_code=400)

    encrypted_value = encrypt_value(sanitized)

    async with AsyncSessionLocal() as session:
        async with session.begin():
            stmt = insert(UserCredentialORM).values(
                user_id=user_id,
                platform=normalized,
                token_value=encrypted_value,
            ).on_conflict_do_update(
                index_elements=["user_id", "platform"],
                set_={"token_value": encrypted_value, "updated_at": _now()},
            )
            await session.execute(stmt)

        result = await session.execute(
            select(UserCredentialORM).where(
                UserCredentialORM.user_id == user_id,
                UserCredentialORM.platform == normalized,
            )
        )
        credential = result.scalar_one()
        credential.token_value = sanitized
        return credential


def build_credential_response_payload(credential: UserCredentialORM) -> dict[str, Any]:
    meta = PLATFORM_WHITELIST[credential.platform]
    if meta.get("credential_kind") == "cookie_file":
        token_value = None
        cookie_fields = get_cookie_fields_for_display(credential.user_id, credential.platform)
    else:
        token_value = _resolve_token_value(credential.token_value)
        cookie_fields = None
    payload = {
        "id": credential.id,
        "platform": credential.platform,
        "label": meta["label"],
        "masked_value": mask_credential(token_value),
        "created_at": credential.created_at,
        "updated_at": credential.updated_at,
    }
    if cookie_fields is not None:
        payload["cookie_fields"] = cookie_fields
    return payload


def _is_cookie_file_platform(platform: str) -> bool:
    meta = PLATFORM_WHITELIST.get(platform, {})
    return meta.get("credential_kind") == "cookie_file"


def get_cookie_storage_dir(user_id: str, platform: str) -> "Path":
    validated = validate_platform(platform)
    meta = PLATFORM_WHITELIST[validated]
    cookie_dir = meta.get("cookie_dir", validated)
    return Path("data") / "cookies" / user_id / cookie_dir


def get_cookie_file_path(user_id: str, platform: str) -> "Path":
    return get_cookie_storage_dir(user_id, platform) / "cookies.txt"


def parse_netscape_cookie_file(file_path: "Path") -> dict[str, str]:
    cookies: dict[str, str] = {}
    with open(file_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.split("\t")
            if len(parts) >= 7:
                name, value = parts[5], parts[6]
                cookies[name] = value
    return cookies


def validate_cookie_file(platform: str, file_path: "Path") -> dict[str, Any]:
    import os
    from datetime import datetime

    validated = validate_platform(platform)
    meta = PLATFORM_WHITELIST[validated]
    required_keys = list(meta.get("required_cookie_keys", []))

    result = {
        "platform": validated,
        "file_exists": False,
        "file_date": None,
        "found_keys": [],
        "missing_keys": [],
        "valid": False,
    }

    if not file_path.exists():
        return result

    result["file_exists"] = True
    try:
        mtime = os.path.getmtime(str(file_path))
        result["file_date"] = datetime.fromtimestamp(mtime).isoformat()
    except OSError:
        pass

    try:
        cookies = parse_netscape_cookie_file(file_path)
    except Exception:
        result["missing_keys"] = required_keys
        return result

    for key in required_keys:
        if key in cookies :
            result["found_keys"].append(key)
        else:
            result["missing_keys"].append(key)

    result["valid"] = len(result["missing_keys"]) == 0
    return result


def resolve_cookie_file_path(user_id: str, platform: str) -> str | None:
    validated = validate_platform(platform)
    meta = PLATFORM_WHITELIST[validated]

    env_var = meta.get("env_var")
    if env_var:
        env_path = os.environ.get(env_var)
        if env_path:
            return env_path

    # Check legacy file on disk
    user_path = get_cookie_file_path(user_id, platform)
    if user_path.exists():
        return str(user_path)

    # Generate from DB credential
    return generate_cookie_file(user_id, platform)
